export const API_ENDPOINTS = {
  CONTACT_SCREEN: "api/contact-setting",
  FACTS_SCREEN: "api/get_factow-setting",
  CALCULATOR_SCREEN: "api/get_calculator",
  HOME_SCREEN: "api/get-home-screen-setting",
  CONSULTING_SCREEN: "api/get-konsultacja-setting",
  EXAMINATION_SCREEN: "api/examination",
  TEAM_SCREEN: "",
  UX_SCREEN: "",
  SALES_SCREEN: "",
  STRATEGY_SCREEN: "api/get-marketing-strategy",
  OPINION_SCREEN: "",
  ANATOMY_SCREEN: "",
  PRICE_LIST_SCREEN: "",
  LOGO_SCREEN: "api/projektowanie",
};
