"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/organisms/header/Header";
import "bootstrap/dist/css/bootstrap.min.css";
import Footer from "@/components/organisms/footer/Footer";
import { Provider } from "react-redux";
import store from "@/store/store";
import { useEffect, useState } from "react";
import BounceLoader from 'react-spinners/BounceLoader';
//import { ReactLenis } from "@studio-freight/react-lenis";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Simulate loading delay
    const timer = setTimeout(() => {
      setLoading(false);
    }, 2000);

    return () => clearTimeout(timer); // Cleanup timeout
  }, []);
  return (
    <html lang="en">
    <body className={inter.className}>
      {loading ? (
        <div className="loader-container">
        <BounceLoader color="#00bfff" size={50} />
      </div>
      ) : (
        <>
          <Header />
          <Provider store={store}>
            {children}
          </Provider>
          <Footer />
        </>
      )}
    </body>
  </html>
  );
}
